import "oaidl.idl";
import "ocidl.idl";

typedef [v1_enum] enum {
	AA_NONE = 0,
	AA_IAccessible = 1,
	AA_IAccessible2 = 2,
	AA_IUIAutomation = 3
} AvailableAccessibilityAPI ;

typedef INT64(__stdcall *UIEventHandler)(INT64 eventId, AvailableAccessibilityAPI available, LPVOID pInterface);

[
	object,
	dual,
	uuid(E3D70497-4CF1-4211-B314-53D610885658)
]
interface ICoreServer : IDispatch {
	[id(1), local] HRESULT Start();
	[id(2), local] HRESULT Stop();
	[id(3), local] HRESULT SetUIEventHandler([in] UIEventHandler handler);
}
[
	uuid(74FA9410-C4D2-4300-BBBB-4E6230C4F0B4),
	version(1.0),
	helpstring("Type library for audio server")
]
library CoreServerLib {
	importlib("stdole2.tlb");
	[
		uuid(909C2521-B9A3-40C1-9B35-702B5A6AB52D)
	]
	coclass CoreServer
	{
		[default] interface ICoreServer;
	}
}
